### ISSUE TITLE
trying to use your example

### ISSUE THREAD

**Issue by KatLingad** [sesser/Instaphp#64]
did the composer install
included the file to the autoload.php

getting this error when attempting your example:

```
<br />
<b>Fatal error</b>:  Uncaught Instaphp\Exceptions\HttpException: Bad Request in /var/www/html/vendor/instaphp/instaphp/src/Instaphp/Instagram/Instagram.php:364
Stack trace:
#0 /var/www/html/vendor/instaphp/instaphp/src/Instaphp/Instagram/Instagram.php(201): Instaphp\Instagram\Instagram-&gt;parseResponse(Object(GuzzleHttp\Message\Response))
#1 /var/www/html/vendor/instaphp/instaphp/src/Instaphp/Instagram/Media.php(55): Instaphp\Instagram\Instagram-&gt;get('/media/popular', Array)
#2 /var/www/html/testy.php(12): Instaphp\Instagram\Media-&gt;Popular(Array)
#3 {main}
  thrown in <b>/var/www/html/vendor/instaphp/instaphp/src/Instaphp/Instagram/Instagram.php</b> on line <b>364</b><br />
```

**Comment by DiederikVanHoorebeke** [comment]
I have the same issue. :/

**Comment by Jasonspd** [comment]
I have the same issue too. Did you guys find a fix?

**Comment by sesser** [comment]
There is no `/media/popular` endpoint any longer. It should/will be removed from the docs

**Comment by wiardvanrij** [comment]
Could you maybe remove this from the example? :D
